export const SEND_FORGOT_EMAIL_REQUEST = 'SEND_FORGOT_EMAIL_REQUEST';
export const SEND_FORGOT_EMAIL_SUCCESS = 'SEND_FORGOT_EMAIL_SUCCESS';
export const SEND_FORGOT_EMAIL_FAILURE = 'SEND_FORGOT_EMAIL_FAILURE';
